apiVersion: apps/v1
kind: DaemonSet
metadata:
   name: fluentd
   labels:
      app: fluentd
      ssd: "true"
spec:
   selector:
      matchLabels:
         app: fluentd
         ssd: "true"
   template:
      metadata:
         labels:
            app: fluentd
            ssd: "true"
      spec:
         nodeSelector:
           ssd: "true"
         containers:
         -  name: fluentd
            image: fluent/fluentd:v0.14.10
            resources:
               limits:
                  memory: 200Mi
               requests:
                  memory: 200Mi
                  cpu: 100m
            volumeMounts: 
            -  name: varlog
               mountPath: /var/log
            -  name: varlibdockercontainers
               mountPath: /var/log/docker/containers
               readOnly: true
         terminationGracePeriodSeconds: 30
         volumes:
         -  name: varlog
            hostPath:
               path: /var/log
         -  name: varlibdockercontainers
            hostPath:
               path: /var/log/docker/containers