apiVersion: v1
kind: Pod
metadata:
  name: kuard-tls
spec:
  containers:
   - name: kuard-tls-container
     image: docker.io/arockiaanto/kuard-amd64:blue
     imagePullPolicy: Always
     volumeMounts:
      - name: tls-certs
        mountPath: "/tls" 
  imagePullSecrets:
   - name: antos-cred
  volumes:
   - name: tls-certs
     secret:
       secretName: kuard-tls