apiVersion: v1
kind: ConfigMap
metadata:
   name: my-config
   namespace: default
data:
   another-param: another-value
   extra-param: extra-value
   my-config.txt: "parameter1=value1\r\nparameter2=value2"